### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by iamcarbon** [bizzehdee/System.Drawing.PSD#11]
What license is this code released under? Is it possible to commit the licensing text?

Hoping to fork and modernize things (reduce allocations, vectorize code paths, etc).

**Comment by bizzehdee** [comment]
BSD. I will commit a licence when i get chance, but feel free to use it as much as you want.

**Comment by iamcarbon** [comment]
@bizzehdee -- Quick ping. Are you able to commit this so it's official?

**Comment by bizzehdee** [comment]
Sorry, forgot about this. yes i will do

**Comment by bizzehdee** [comment]
Done
