### ISSUE TITLE
ImageDecoder.DecodeImage(PsdFile psdFile); does not support transparent background

### ISSUE THREAD

**Issue by MikaelPorttila** [bizzehdee/System.Drawing.PSD#2]
My .psd file has a transparent background but when i call the DecodeImage-method and pass the loaded PsdFile the result bitmap have a white background color.

Can't find any overloads or settings to change this behavior.

**Comment by bizzehdee** [comment]
To be able to render with transparency, you must render each layer on top of another with multiple calls to DecodeImage(Layer)
