### ISSUE TITLE
layer name do not display correctly if it contains Chinese character!!! 

### ISSUE THREAD

**Issue by DsonKing** [bizzehdee/System.Drawing.PSD#3]

**Comment by bizzehdee** [comment]
Layer names are stored as plain ASCII in PSD's. Then a hidden adjustment layer is added with the UTF8 version. But the UTF8 is in a very strange encoding that makes no sense. I will have to do more investigation or be pointed towards some sort of specification on the matter.

**Comment by bizzehdee** [comment]
This should be fixed with PR #6
